from base64 import b64encode
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "src" / "lib" / "pdfFonts"
OUTPUT = FONT_DIR / "cairoArabicFonts.ts"

lines = [
    "// Generated by scripts/embed-pdf-fonts.py; merged Cairo Arabic/Latin subsets, SIL OFL licensed.",
    "export const cairoArabicFonts = {",
]
for weight, name in ((400, "regular"), (700, "bold")):
    data = b64encode((FONT_DIR / f"cairo-{weight}.ttf").read_bytes()).decode("ascii")
    lines.append(f"  {name}: '{data}',")
lines.extend(["} as const;", ""])
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"created {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
